### ISSUE TITLE
Add rustup setting to nightly in README

### ISSUE THREAD

**Issue by Nizerlak** [tfpk/macrokata#11]
There's lack of `rustup default nightly` step in 'Getting Started ' section of README, which result in inability of cargo to find certain dependencies (such as clap in 4.0.17 version). After execution of mentioned command everything works fine.

**Comment by tfpk** [comment]
Hi!

I'm definitely wary of asking people to change their default compiler -- that feels like a significant request.

What exactly can't cargo find? I may be misunderstanding the issue.

**Comment by tfpk** [comment]
Closing this as there's no new info. Please do reopen/open a new issue if I am in fact missing something :)
