### ISSUE TITLE
Make Positive Literals Match

### ISSUE THREAD

**Issue by tfpk** [tfpk/macrokata#16]
Perhaps unrelated, but would it be better for positive literal to be

```rust
( $(+)?$positive: literal ) => {...}
```

So the macro works for `+5` as well as `5`?

_Originally posted by @dong-zh in https://github.com/tfpk/macrokata/issues/9#issuecomment-1292259182_

**Comment by insou22** [comment]
Not sure if this is entirely necessary since Rust doesn't support unary `+` in the first place?

**Comment by tfpk** [comment]
Fair point -- on that basis, I'm going to close this as wontfix.
