### ISSUE TITLE
Project does not build on stable toolchain

### ISSUE THREAD

**Issue by Nizerlak** [tfpk/macrokata#32]
First of all, sorry for that I wasn't specific about the actual issue in #11. The problem was I couldn't build the first exercise following the instruction.
Command: `cargo run -- test 01_my_first_macro` 
Received error:
```shell
    Blocking waiting for file lock on package cache
    Updating crates.io index
error: failed to select a version for the requirement `clap = "^4.0.17"`
candidate versions found which didn't match: 3.2.23, 3.2.22, 3.2.21, ...
location searched: crates.io index
required by package `macrokata v0.1.0
```

Setting toolchain to nightly resolved the issue. However @tfpk said in #11 that it would be inappropriate to force anyone to change the compiler. Is there any other way to build and run exercises without setting toolchain to nightly?

**Comment by tfpk** [comment]
Hi!

This might be a really silly question; but you could please check what your current stable version/toolchain is with `rustup show`?

I used `cargo +stable build --bin 01_my_first_macro_soln`; and my `rustup show` says I'm on:

```
Default host: x86_64-unknown-linux-gnu
...
active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.64.0 (a55dd71d5 2022-09-19)
```
So I'm wondering if we're running something different (if we are, then I can test for that platform :) )

**Comment by tfpk** [comment]
Hi!

I'm going to close this issue on Dec 31st unless I've heard anything else. My suspicion is that you're using an older version of Rust, but if you could provide more details on the issue I'd be more than happy to look into it further :)

Thanks again for the issue.
