### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by senekor** [tfpk/macrokata#36]
Hello! First of all, thanks for making this. I just went through the exercises and they were very valuable to me! This is the best macro teaching material I've come across thus far.

I think it would be great to add a license to this project.

For example, I hang out on exercism.org quite a bit. I think this project could be added to the Rust track over there mostly as-is, under a new concept for macros. I'm wondering if the creators of these exercises are open to them being shared in such a way. Adding a license could answer such questions.

**Comment by tfpk** [comment]
Hey! Thanks so much for the kind words :)

Definitely seems reasonable to add a license. My preference would be to keep it standard, and make it MIT/Apache2 Dual License. I'm going to try and reach out to all the contributors who've made non-trivial contributions and get their OK for doing that; then I'll change the license.

As for adding it to exercism.org -- the more people it helps, the better! My only worry would be that we end up with two seperate "MacroKata"s being maintained separately. I don't think it'd be good to move everything just to Exercism (apart from anything else, this is already being used as teaching material in one university, and it wouldn't be appropriate to ask students to sign up for a service like that IMO). If there's interest in having it on Exercism, it'd be good if we could have some mechanism of keeping them in sync.

**Comment by tfpk** [comment]
@light4 -- sorry to tag you here, but could you get in touch if you'd be OK licensing your contribution under MIT/Apache2 Dual License?

**Comment by light4** [comment]
OK

**Comment by tfpk** [comment]
Hi @remlse

I hereby license all the work in the repo as MIT or Apache-2, at your option.

I'm going to close this issue. If you (or anyone else) are interested in copying things over to exercism; I'd be very grateful if you could setup another issue so we can discuss what sharing content between here and there might look like.

**Comment by senekor** [comment]
Thank you very much!

> My only worry would be that we end up with two seperate "MacroKata"s being maintained separately.

That's a valid concern. I will get in touch with other maintainers at exercism about the idea to add these exercises and make sure to get in contact with you via a new issue.
