### ISSUE TITLE
cargo run -- test 01_my_first_macro fails

### ISSUE THREAD

**Issue by akhildevelops** [tfpk/macrokata#47]
I've got below error for comparing the macro I built with the solution. 

`cargo run -- test 01_my_first_macro`
``` rust
vscode ➜ ~/macrokata (main) $ cargo run -- test 01_my_first_macro
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/macrokata test 01_my_first_macro`
Got some errors when expanding the macro:

    Checking macrokata v0.3.1 (/home/vscode/macrokata)
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
```

Surprisingly, cargo expand, if run seperately, shows me the expanded macro without any errors:
`cargo run -- test 01_my_first_macro`
``` rust
vscode ➜ ~/macrokata (main) $ cargo expand --color "always" --bin 01_my_first_macro
    Checking macrokata v0.3.1 (/home/vscode/macrokata)
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s

#![feature(prelude_import)]
#[prelude_import]
use std::prelude::rust_2021::*;
#[macro_use]
extern crate std;
fn show_output() {
    {
        ::std::io::_print(format_args!("I should appear as the output.\n"));
    }
}
fn main() {
    show_output()
}
```
Below is the output of `cargo expand --color "always" --bin 01_my_first_macro main` that's actually executed in https://github.com/tfpk/macrokata/blob/bbec43eabceaccac2c329489eb2fabf9cd259057/src/test.rs#L14-L22
```rust
vscode ➜ ~/macrokata (main) $ cargo expand --color "always" --bin 01_my_first_macro main
    Checking macrokata v0.3.1 (/home/vscode/macrokata)
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s

fn main() {
    show_output()
}
```

**Comment by OneMore14** [comment]
this may be helpful   https://github.com/tfpk/macrokata/pull/46

**Comment by akhildevelops** [comment]
I observed that `cargo` streams it's output to stderr even when the build is run without errors.
Running this `cargo expand --color "always" --bin 01_my_first_macro main` gives:
```rust
vscode ➜ ~/macrokata (main) $ cargo expand --color "always" --bin 01_my_first_macro main
    Checking macrokata v0.3.1 (/home/vscode/macrokata)
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s

fn main() {
    show_output()
}
```

But if I just stream stdout, this is the output:
```rust
vscode ➜ ~/macrokata (main) $ cargo expand --color "always" --bin 01_my_first_macro main 2>/dev/null
fn main() {
    show_output()
}
```

I gave a PR that tries to solves this: https://github.com/tfpk/macrokata/pull/48

**Comment by tfpk** [comment]
Hopefully #49 fixes this :) Let me know if you spot any issues, otherwise I'll merge in a few days.

**Comment by akhildevelops** [comment]
I've tested seems ok.

**Comment by tfpk** [comment]
#49 merged, so closing this.
