### ISSUE TITLE
Exercise 12 idea is vague to grasp

### ISSUE THREAD

**Issue by skaunov** [tfpk/macrokata#54]
I'm not sure I've got everything correctly here --- it's not easy to reason on something you're still learning --- so bear with me, pls. X)

I decided to try to solve the exercise without using material from the relevant page to see what would happen and what problems do we actually shoot.

So the solution is straightforward af.
```rust
macro_rules! coord {
    ($x:expr, $y:expr) => {super::Coordinate{x: $x, y: $y}};
    ($x:expr, $y:expr, $z:expr) => {super::third_dimension::Coordinate{
        x: $x, y: $y, z: $z
    }};
    ($x:expr, $y:expr, $z:expr, $t:expr) => {fourth_dimension::Coordinate{
        x: $x, y: $y, z: $z, t: $t
    }};
}
```

Beautiful `makrokata` tells me that I kinda ignored the task, which is fairly expected.
`...`
```console
The diff is:

@@ -1,5 +1,5 @@
 fn main() {
-    let four_dim = fourth_dimension::Coordinate {
+    let four_dim = crate::fourth_dimension::Coordinate {
         x: 1,
         y: 2,
         z: 3,
```

Now let's see how miserably we let the exercise down with this awful short-cut.
```bash
$ cargo run --bin 12_hygienic_macros
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `/home/[REDACTED]/Desktop/macrokata/target/debug/12_hygienic_macros`
Coordinate { x: 1, y: 2 }
```

This irony bring no offense with it, just to skim the story. I have no idea atm how to remediate the thing, and does it even needs remediation. I'm not really getting this last segment of `macrokata` yet, but feel like something not entirely right here. _So my main question: was this intended, did I something plainly wrong?_

**Comment by tfpk** [comment]
The approach you've taken is the right one (i.e. using three matchers which create the second, third and fourth dimension structs). 

The idea here though is learning to use the `$crate` metavariable. You'll notice that in your solution, you've hardcoded the `super`. That works in this example, but doesn't work more generally.

Imagine you add in this, just before the main function:

```rust
impl Coordinate {
    pub fn to_3d(self) -> third_dimension::Coordinate {
        coord!(self.x, self.y, 0)
    }
}
```

It won't work! Try and figure out why, and hopefully you'll see the point of the exercise better.

IF that works, let me know, and I'll add the code snippet to the exercise.

**Comment by skaunov** [comment]
This whole issue/story is a bloated way to ask _if we can elaborate the exercise so that use of this metavariable would be immenent_. The point is clear initially from the description yeah, but not the idea, you know. I mean gradual solving the problems is really valuable part of your kata! And in this case the problem itself so easily bypassed that is hard to _feel_ what is being solved. X)

Thank you for the snippet — will return to it later. (Now it's me via a handheld.)

**Comment by skaunov** [comment]
(I'm in progress, will return after some other stuff.)

**Comment by skaunov** [comment]
"I approve!" X)
> IF that works, let me know, and I'll add the code snippet to the exercise.

Now fingers really want to add `crate` (and then remember to add `$`) quite naturally! Fourth dimension works as it were, obviously. X)
```rust
macro_rules! coord {
    ($x:expr, $y:expr) => {$crate::Coordinate{x: $x, y: $y}};
    ($x:expr, $y:expr, $z:expr) => {
        $crate::third_dimension::Coordinate{x: $x, y: $y, z: $z}
    };
    ($x:expr, $y:expr, $z:expr, $t:expr) => {fourth_dimension::Coordinate{x: $x, y: $y, z: $z, t: $t}};
}
```

(Let me leave closing this issue to you, so it could be instrumental in this small upgrade.)

**Comment by skaunov** [comment]
btw, the second half of the chapter is quite important too \
I never thought without it I shouldn't rely on `cargo-expand` that much \
just used it; never ever _seeing_ the disclaimer

And only now I appreciated meaning of this second half, since previously mind was focused on the first half.

It's just another piece of feedback. I have no idea how to improve. But this second half is left quite unnoticed (at least by me). Also I remember how I "expanded" the example in mind, but only today when went deeper, and clicked the link to `cargo-expand` from Chapter 12 I had _aha moment_, and now writing how underappreciated this second half was. X)

**Comment by tfpk** [comment]
I've added some more text here, will see if we get any more feedback on this before doing more changes. Thanks so much for your comments.
